exports.socketEvents = {
  ENTER_ROOM: 'ENTER_ROOM',
  LEAVE_ROOM: 'LEAVE_ROOM',
  SEND_MESSAGE: 'SEND_MESSAGE',
  RECEIVE_MESSAGE: 'RECEIVE_MESSAGE',
  CHECK_ROOM_PARTICIPANTS: 'CHECK_ROOM_PARTICIPANTS',
  ROOM_PARTICIPANTS: 'ROOM_PARTICIPANTS',
};
